@apiURL = https://login-api-projekt1.onrender.com/users

POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "raholmti@arcada.fi",
    "password": "hemlis"
}
###

POST {{apiURL}}/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm1haWwiOiJyYWhvbG10aUBhcmNhZGEuZmkiLCJuYW1lIjoiVGludGluIiwiaWF0IjoxNzYwMDA0MDgwLCJleHAiOjE3NjI1OTYwODB9.p3AOLNBp8jJ9s8xPBGFXgO4-s0t74e3NcoRs91V-Y7k

{
    "id": 6
}

###

DELETE {{apiURL}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm1haWwiOiJyYWhvbG10aUBhcmNhZGEuZmkiLCJuYW1lIjoiVGludGluIiwiaWF0IjoxNzU5OTk3ODk4LCJleHAiOjE3NjI1ODk4OTh9.8-eXtPeA7-3RgPiGeA79WdzXrImjtlPycagT_5-pbSI