@apiURL = https://login-api-projekt1.onrender.com/users

POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "raholmti@arcada.fi",
    "password": "hemlis"
}
###

DELETE {{apiURL}}/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm1haWwiOiJyYWhvbG10aUBhcmNhZGEuZmkiLCJuYW1lIjoiVGludGluIiwiaWF0IjoxNzU5OTkyODIzLCJleHAiOjE3NjI1ODQ4MjN9.1iFEkMy2kIkHciuBQwy8kgFFJmR7WMDwtL7ae3E3oM4